<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <NoWarn>CA2007</NoWarn>
    <UserSecretsId>e8781cb5-8be0-48e7-b453-460e2ff4ac02</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Htmx" Version="1.9.0" />
    <PackageReference Include="Htmx.TagHelpers" Version="1.9.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.10" />
    <PackageReference Include="SonarAnalyzer.Csharp" Version="10.15.0.120848">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HtmxProject.Application\HtmxProject.Application.csproj" />
    <ProjectReference Include="..\HtmxProject.Database\HtmxProject.Database.csproj" />
  </ItemGroup>

</Project>
